#!/usr/bin/env python3
"""
2D Anderson Hamiltonian on a torus: H = -Δ + V with periodic boundary conditions.
Computes a few lowest eigenpairs and shows ONLY 3D eigenfunction-density surfaces over the domain [0,L)^2.

Key plotting choices:
- Plot z = log10(|psi|^2) to reveal localization tails.
- Use ONE shared color scale across all eigenfunctions so plots are comparable.
- Control dynamic range in decades (orders of magnitude) below each plot's peak.

Dependencies: numpy, scipy, matplotlib
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.sparse import lil_matrix
from scipy.sparse.linalg import eigsh
import matplotlib.colors as mcolors


def periodic_laplacian_2d(N: int, L: float):
    """Sparse matrix for (-Δ_h) with periodic BC on an N×N grid over [0,L)^2."""
    h = L / N
    n = N * N
    A = lil_matrix((n, n), dtype=np.float64)

    def idx(i, j):
        return (i % N) * N + (j % N)

    c = 1.0 / (h * h)
    for i in range(N):
        for j in range(N):
            p = idx(i, j)
            A[p, p] = 4.0 * c
            A[p, idx(i + 1, j)] = -c
            A[p, idx(i - 1, j)] = -c
            A[p, idx(i, j + 1)] = -c
            A[p, idx(i, j - 1)] = -c

    return A.tocsr(), h


def gaussian_random_field_periodic(N: int, L: float, corr_length: float, seed: int = 0):
    """
    Periodic real Gaussian random field generated by filtering white noise in Fourier space.
    Filter: exp(-0.5 * |k|^2 * corr_length^2). Smaller corr_length -> rougher potential.
    Normalized to mean 0, std 1.
    """
    rng = np.random.default_rng(seed)
    w = rng.standard_normal((N, N))
    W = np.fft.fft2(w)

    k = 2.0 * np.pi * np.fft.fftfreq(N, d=L / N)
    kx, ky = np.meshgrid(k, k, indexing="ij")
    k2 = kx * kx + ky * ky

    filt = np.exp(-0.5 * k2 * (corr_length ** 2))
    V = np.fft.ifft2(W * filt).real
    V -= V.mean()
    V /= (V.std() + 1e-12)
    return V


def build_anderson_hamiltonian(N=220, L=1.0, disorder_strength=12.0, corr_length=0.01, seed=0):
    """H = -Δ_h + disorder_strength * V with periodic BC."""
    Lap, h = periodic_laplacian_2d(N, L)
    V = gaussian_random_field_periodic(N, L, corr_length, seed=seed)
    V = disorder_strength * V

    H = Lap.tolil()
    H.setdiag(H.diagonal() + V.reshape(-1))
    return H.tocsr(), V, h


def compute_lowest_eigenpairs(H, k=6):
    """Compute k smallest algebraic eigenvalues/eigenvectors of sparse symmetric H."""
    evals, evecs = eigsh(H, k=k, which="SA")
    order = np.argsort(evals)
    return evals[order], evecs[:, order]


def densities_from_evecs(evecs, N):
    dens = []
    for i in range(evecs.shape[1]):
        psi = evecs[:, i].reshape(N, N)
        dens.append((psi * psi).real)  # real symmetric matrix -> real eigenvectors
    return dens


def plot_densities_3d_one_figure(dens_list, evals, N, L, decades=10, elev=35, azim=-60):
    """
    One figure containing multiple 3D surfaces (no torus, no decay plot).
    z = log10(|psi|^2), with shared color normalization across all eigenfunctions.
    decades controls how far below the GLOBAL peak we show.
    """
    k = len(dens_list)

    # Grid
    x = np.linspace(0, L, N, endpoint=False)
    y = np.linspace(0, L, N, endpoint=False)
    X, Y = np.meshgrid(x, y, indexing="ij")

    # Convert to log-density
    logs = [np.log10(d + 1e-16) for d in dens_list]

    # Shared color scale across all subplots
    global_vmax = max(np.max(Z) for Z in logs)
    global_vmin = global_vmax - decades

    norm = mcolors.Normalize(vmin=global_vmin, vmax=global_vmax)
    cmap = plt.cm.viridis

    # Layout
    ncols = int(np.ceil(np.sqrt(k)))
    nrows = int(np.ceil(k / ncols))

    fig = plt.figure(figsize=(5.5 * ncols, 4.8 * nrows))

    for i, Z in enumerate(logs):
        ax = fig.add_subplot(nrows, ncols, i + 1, projection="3d")

        Zc = np.clip(Z, global_vmin, global_vmax)
        facecolors = cmap(norm(Zc))

        ax.plot_surface(X, Y, Zc, facecolors=facecolors, linewidth=0, antialiased=True, shade=False)
        ax.set_xlabel("x")
        ax.set_ylabel("y")
        ax.set_zlabel("log10(|ψ|²)")
        ax.view_init(elev=elev, azim=azim)
        ax.set_zlim(global_vmin, global_vmax)
        ax.set_title(fr"k={i+1},  λ={evals[i]:.6f}")

    # One shared colorbar for the whole figure
    m = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    m.set_array([])
    cbar = fig.colorbar(m, ax=fig.axes, shrink=0.6, pad=0.02)
    cbar.set_label("log10(|ψ|²) (shared scale)")

    fig.tight_layout()
    plt.show()


def main():
    # ---------- Parameters ----------
    N = 500                  # reduce if slow
    L = 1.0
    seed = 2
    k_eigs = 4

    disorder_strength = 14.0
    h = L / N
    corr_length = h    # smaller -> rougher -> often stronger localization

    # Plot settings
    decades = 12             # show tails down to 10–14 decades below the global peak

    # ---------- Build, solve ----------
    H, V, h = build_anderson_hamiltonian(
        N=N, L=L,
        disorder_strength=disorder_strength,
        corr_length=corr_length,
        seed=seed
    )
    evals, evecs = compute_lowest_eigenpairs(H, k=k_eigs)
    dens_list = densities_from_evecs(evecs, N)

    # ---------- Plot only eigenfunction densities on the domain ----------
    plot_densities_3d_one_figure(dens_list, evals, N, L, decades=decades)


if __name__ == "__main__":
    main()